# Generated by Django 4.2.11 on 2025-12-23 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_sales_cashier_receipt_cashier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='cashier',
        ),
        migrations.AddField(
            model_name='sales',
            name='cashier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
