# Generated by Django 4.2.11 on 2025-12-26 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_receipt_cashier_sales_cashier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('sale', 'Sale Made'), ('product_add', 'Product Added'), ('product_update', 'Product Updated'), ('product_delete', 'Product Deleted'), ('stock_update', 'Stock Updated'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('user_register', 'User Registered'), ('category_add', 'Category Added'), ('category_update', 'Category Updated'), ('category_delete', 'Category Deleted')], max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('related_object', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
