# Generated by Django 4.2.11 on 2025-12-26 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
